datacenter: dc1
racks:
  - name: rack1
    members: 2
    storage:
      storageClassName: yc-network-ssd
      capacity: 10Gi
    resources:
      limits:
        cpu: 1
        memory: 4Gi   # Scylla requires >= 1 GiB per shard; operator/cgroup can reduce what process sees
      requests:
        cpu: 1
        memory: 4Gi
