scylla:
  datacenter: manager-dc
  racks:
    - name: manager-rack
      members: 1
      storage:
        storageClassName: yc-network-ssd
        capacity: 8Gi
      resources:
        limits:
          cpu: 1
          memory: 4Gi   # same as main cluster: Scylla needs >=1Gi/shard
        requests:
          cpu: 1
          memory: 4Gi
